build:
  ruby: '2.1.5'
  before:
    - "{{cd}} cp config/database.yml.example config/database.yml"
    - "mysqladmin create redmine_test -u root -S /tmp/mysql.sock"
    - "{{cd}} RAILS_ENV=test {{rvm}} bundle exec rake db:migrate"
    - "rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Minsk /etc/localtime"
